server:
  port: 11080
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  servlet:
    context-path:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  application:
    name: springboot2-jar
  banner:
    location: classpath:banner/banner.txt
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/caop?userSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#          username: root
#          password: mysql
#          driver-class-name: com.mysql.cj.jdbc.Driver
# 配置日志
#mybatis-plus:
#  mapper-locations: classpath:com/example/springboot2/dao/mapper/**.xml # 指定mybatis-plus写sql的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    banner: false